[Configuration]
#-------------------------------------------------------
AlwaysCopyInBackground=1
SpecialCursorMovement=1
StartupScreen=0
#-------------------------------------------------------
InstallDir=c:\totalcmd
languageini=wcmd_rus.lng
Mainmenu=wcmd_rus.mnu
UseNewDefFont=1
SetEncoding=дц.do.not.remove
firstmnu=3123
FirstTime=0
FirstTimeIconLib=0
SeparateTree=0
PanelsVertical=0
Aligned extension=1
test=30
MinIconWidth=0
MinLineHeight=0
ShowHiddenSystem=1
UseLongNames=1
Small83Names=0
OldStyleTree=0
autotreechange=0
DirBrackets=1
ShowParentDirInRoot=1
SortDirsByName=1
Tips=3
FileTipWindows=0
Win32TipWindows=0
SortUpper=0
IconOverlays=0
IconsSpecialFolders=3
Showicons=2
ShowEXEandLNKicons=2
IconsInMenus=17
IconsOnNet=1
onlyonce=1
TrayIcon=1
UseRightButton=1
Savepath=1
Savepanels=1
MarkDirectories=1
AlwaysToRoot=0
SingleClickStart=0
RenameSelOnlyName=0
SaveCommands=0
SaveHistory=0
EverythingForSize=0
CountSpace=0
CountMarked=1
1hourdif=0
CopyComments=6
CommentPreferredFormat=4
IconClickSelection=1
LogOptions=7198
LogRotateLimit=0
LogKeepCount=30
DirTabOptions=824
DirTabLimit=32
ExplorerForCopy=0
Win95Delete=0
UseTrash=1
Viewer=none
Editor=notepad
Viewertype=1
ShowCentury=1
SizeStyle=1
SizeFooter=1
LastSearchOptions=32
QuickSearchAutoFilter=1
AltSearch=2
QuickSearchMatchBeginning=1
QuickSearchExactMatch=0
CompareCaseSensitive=0
CompareIgnoreRepSpace=1
CompareIgnoreRepeatedLines=1
CompareVertical=0
CompareBytesPerLine=8
WatchDirs=1
SoundDelay=-10
WarnMissingExtensions=0
FirstTimeUnpack=0
pluginbasedir=C:\totalcmd\plugins
FirstTimeZIP=0
SyncFlags=1
SyncButtons=55
lastmd5=1
CrcSeparateFiles=0
CrcSeparateFolders=0
[ButtonbarCache]
IconDll_default.bar=TCNewLib1
IconDll_vertical.bar=TCNewLib1
[FileSystemPlugins64]
$checksum$=3014672
[left]
path=C:\Users\norden\
ViewMode=10001
activepanelcolor=-1
activepanelcolor2=-1
ShowAllDetails=1
StartupScreen=0
SpecialView=3
show=1
negative Sortorder=0
customsortorder=0
userspec=*.txt
activepanelcolordark=-1
activepanelcolordark2=-1
[right]
path=c:\
ViewMode=0
activepanelcolor=-1
activepanelcolor2=-1
ShowAllDetails=1
SpecialView=3
show=1
negative Sortorder=0
customsortorder=0
userspec=*.txt
activepanelcolordark=-1
activepanelcolordark2=-1
[1366x768 (8x16)]
maximized=1
x=54
y=19
dx=1269
dy=698
Divider=500
DividerQuickView=500
DividerComments=500
Tabstops=269,282,334,218,790,103
Iconsize32=22 
CustColumnX=354
CustColumnY=164
CustColumnDX=657
CustColumnDY=400
CustColumnMax=0
PluginSelX=832
PluginSelY=163
PluginSelDX=480
PluginSelDY=480
PluginSelMax=0
MenuChangeX=363
MenuChangeY=164
MenuChangeDX=640
MenuChangeDY=400
MenuChangeMax=0
RenameX=71
RenameY=46
RenameDX=1222
RenameDY=638
RenameMax=0
RenameTabs=232,323,581,656,762
ConnectX=440
ConnectY=164
ConnectDX=485
ConnectDY=400
ConnectMax=0
SearchX=319
SearchY=71
SearchDX=838
SearchDY=264
SearchMax=0
CompareX=89
CompareY=24
CompareDX=1226
CompareDY=658
CompareMax=0
CompareDivider=500
TreeDlgX=268
TreeDlgY=60
TreeDlgDX=878
TreeDlgDY=581
TreeDlgMax=0
CmdSelX=359
CmdSelY=173
CmdSelDX=653
CmdSelDY=371
CmdSelMax=0
SyncX=126
SyncY=51
SyncDX=1124
SyncDY=600
SyncMax=0
SyncTabs=92,152,247,270,362,422
[Tabstops]
0=358
1=371
3=423
4=307
6=968
5=103
AdjustWidth=1
[Layout]
ButtonBar=0
ButtonBarVertical=0
DriveBar1=0
DriveBar2=1
DriveBarFlat=1
InterfaceFlat=0
DriveCombo=1
DirectoryTabs=1
XPthemeBg=0
CurDir=1
TabHeader=1
StatusBar=0
CmdLine=0
KeyButtons=1
HistoryHotlistButtons=1
BreadCrumbBar=1
[Colors]
InverseCursor=0
ThemedCursor=1
InverseSelection=0
BackColor=-1
BackColor2=15000804
ForeColor=-1
MarkColor=-1
CursorColor=-1
CursorText=-1
ActiveTitle=13275904
[Buttonbar]
DefaultLib=wcmicon2
[ListerPlugins64]
$checksum$=3014672
[CustomFields]
Widths1=244,41,-72,-60
Options1=1936|0|96
AutoLoad=0
Titles=MyColums|MyColums2
Headers1=Модификаиця\nРазмер [Байт]
Contents1=[=tc.writedate]\n[=tc.size.bytes]    
Widths2=320,58
Options2=1382|0|96
[ContentPlugins64]
$checksum$=3014672
[RenameTemplates]
0=[C]
1=[N][C]
2=[N]
[RightHistory]
[LeftHistory]
[Selection]
0=*.txt
1=*.*
2=*.sys
[NewFileHistory]
0=123
1=1.txt
2=.gitignore
3=1
4=ууу
[ViewModes]
0_name=<По умолчанию>
0_icon=
0_options=-1|-1|0||-1|-1|-1
[MkDirHistory]
0=Практика Созыкин
1=1
2=2
3=Лекции Демин
4=Универ
5=My2
6=My1
[Shortcuts]
CAS+E=cm_MatchSrc
CAS+D=cm_CompareFilesByContent
CS+OEM_US\|=cm_MatchSrc
CA+OEM_<\>=cm_MatchSrc
CA+OEM_US\|=cm_MatchSrc
[Confirmation]
deleteDirs=0
OverwriteFiles=1
OverwriteReadonly=0
OverwriteHidSys=0
MouseActions=0
[PackerPlugins]
iso=192,C:\totalcmd\plugins\wcx\ISO\iso.wcx
nrg=192,C:\totalcmd\plugins\wcx\ISO\iso.wcx
img=192,C:\totalcmd\plugins\wcx\ISO\iso.wcx
mdf=192,C:\totalcmd\plugins\wcx\ISO\iso.wcx
7z=223,C:\totalcmd\plugins\wcx\7zip\7zip.wcx
[PackerPlugins64]
$checksum$=1460031504
exts=iso*nrg*img*mdf*7z*
[Packer]
LastUsedPacker64=1
LastUsedPacker=1
InternalZip=1
InternalUnzip=1
zipnt=0
ZIP=pkzip.exe
UnZIP=pkunzip.exe
InternalZipRate=9
Zip83Name=0
ZipSetDateToNewest=0
nodelete=0
OpenPartial=0
UnZIPOverwrite=1
[Lister]
Codepage=1251
[DirMenu]
menu1=Универ
cmd1=cd C:\Users\NordeN\YandexDisk\Универ
menu2=YandexDisk
cmd2=cd C:\Users\NordeN\YandexDisk
menu3=NordeN
cmd3=cd c:\Users\NordeN
menu4=Downloads
cmd4=cd c:\Users\NordeN\Downloads
menu5=Desktop
cmd5=cd c:\Users\NordeN\Desktop
[1920x1080 (8x16)]
FontSize=10
FontName=Cascadia Mono
FontCharset=204
FontSizeWindow=9
FontNameWindow=Cascadia Mono
FontCharsetWindow=204
FontWeight=400
FontWeightWindow=400
FontNameDialog=Microsoft Sans Serif
FontCharsetDialog=1
Iconsize32=25
Iconsize32_dpi=96
Tabstops=358,371,423,307,968,103
maximized=1
x=410
y=116
dx=1100
dy=800
Divider=500
DividerQuickView=500
DividerComments=500
[AllResolutions]
FontSize=10
FontName=Cascadia Mono
FontCharset=204
FontSizeWindow=9
FontNameWindow=Cascadia Mono
FontCharsetWindow=204
FontWeight=400
FontWeightWindow=400
FontNameDialog=Microsoft Sans Serif
FontCharsetDialog=1
